import Logo from "./images/logo.svg"
import Search from "./images/search.svg"
import Cart from "./images/cart.svg"
import Profile from "./images/profile.svg"
import Payment from "./images/payment.svg"
import Return from "./images/return.svg"
import Contact from "./images/contact.svg"
import Facebook from "./images/facebook.svg"
import Instagram from "./images/instagram.svg"
import Linkedin from "./images/linkedin.svg"
import Dribble from "./images/dribble.svg"
import X from "./images/x.svg"
import Menuicon from "./images/menu-icon.svg"

export {Logo, Search, Cart, Profile, Payment, Return, Contact, Facebook, Instagram, Linkedin, Dribble, X, Menuicon}